/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

println("Configuring ${project.path} project...")

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("shared:B")
    implementation("shared:C")
    implementation("org.apache.commons:commons-text")
    // Break the App build by adding an invalid dependency.
    // This will demonstrate that the composite build (shared) even though successful will not be saved and reloaded
    // from the configuration cache separately from the entire project as a whole.
    // If composite builds could be built once and configuration cache reused separately from the calling build,
    // this would improve performance of the configuration dramatically in larger apps.
    implementation("<break build with invalid dependency>")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.AppKt"
}
