/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app

import org.apache.commons.text.WordUtils

fun main() {
    val result = "hello world!"
    println(WordUtils.capitalize(result))
}
